version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - errchkjson
    - errname
    - errorlint
    - fatcontext
    - nilerr
    - noctx
    - predeclared
    - tparallel
    - unconvert
    - unparam
    - wastedassign
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (*bytes.Buffer).Write
        - (*bytes.Buffer).WriteString
        - (*bytes.Buffer).WriteByte
        - (*bytes.Buffer).WriteRune
        - (*strings.Builder).Write
        - (*strings.Builder).WriteString
        - (*strings.Builder).WriteByte
        - (*strings.Builder).WriteRune
        - hash.Hash.Write
        - (io.Closer).Close
        - (io.ReadCloser).Close
        - (net.Listener).Close
    staticcheck:
      checks:
        - "SA*"
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - errchkjson
          - ineffassign
          - noctx
          - staticcheck
          - unparam
          - unused
          - wastedassign
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
