run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - typecheck
    - unused
    - errname
    - bodyclose
    - nilerr
    - copyloopvar
    - errorlint
    - errchkjson
    - noctx
    - fatcontext
    - tparallel
    - unparam
    - predeclared
    - wastedassign
    - unconvert

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (*bytes.Buffer).Write
      - (*bytes.Buffer).WriteString
      - (*bytes.Buffer).WriteByte
      - (*bytes.Buffer).WriteRune
      - (*strings.Builder).Write
      - (*strings.Builder).WriteString
      - (*strings.Builder).WriteByte
      - (*strings.Builder).WriteRune
      - hash.Hash.Write
      - (io.Closer).Close
      - (io.ReadCloser).Close
      - (net.Listener).Close

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - errchkjson
        - ineffassign
        - staticcheck
        - unused
        - noctx
        - unparam
        - wastedassign
