//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ScreenAdvanceRequestDirection.
const (
	Next ScreenAdvanceRequestDirection = "next"
	Prev ScreenAdvanceRequestDirection = "prev"
)

// Defines values for VideoActionRequestAction.
const (
	Pause          VideoActionRequestAction = "pause"
	Play           VideoActionRequestAction = "play"
	TogglePlayback VideoActionRequestAction = "toggle_playback"
)

// Defines values for VideoPlayerStateRequestPlayerState.
const (
	VideoPlayerStateRequestPlayerStateBuffering VideoPlayerStateRequestPlayerState = "buffering"
	VideoPlayerStateRequestPlayerStatePaused    VideoPlayerStateRequestPlayerState = "paused"
	VideoPlayerStateRequestPlayerStatePlaying   VideoPlayerStateRequestPlayerState = "playing"
)

// Defines values for VideoPlayerStateResponsePlayerState.
const (
	VideoPlayerStateResponsePlayerStateBuffering VideoPlayerStateResponsePlayerState = "buffering"
	VideoPlayerStateResponsePlayerStatePaused    VideoPlayerStateResponsePlayerState = "paused"
	VideoPlayerStateResponsePlayerStatePlaying   VideoPlayerStateResponsePlayerState = "playing"
)

// Defines values for VideoStateResponseMode.
const (
	Video   VideoStateResponseMode = "video"
	Widgets VideoStateResponseMode = "widgets"
)

// Defines values for VideoStreamPlayerState.
const (
	VideoStreamPlayerStateBuffering VideoStreamPlayerState = "buffering"
	VideoStreamPlayerStatePaused    VideoStreamPlayerState = "paused"
	VideoStreamPlayerStatePlaying   VideoStreamPlayerState = "playing"
)

// Defines values for VideoStreamPriority.
const (
	VideoStreamPriorityPersistent VideoStreamPriority = "persistent"
	VideoStreamPriorityTemporary  VideoStreamPriority = "temporary"
)

// Defines values for VideoStreamType.
const (
	VideoStreamTypeHls    VideoStreamType = "hls"
	VideoStreamTypeMjpeg  VideoStreamType = "mjpeg"
	VideoStreamTypeWebrtc VideoStreamType = "webrtc"
)

// Defines values for VideoTriggerRequestPlayerState.
const (
	VideoTriggerRequestPlayerStateBuffering VideoTriggerRequestPlayerState = "buffering"
	VideoTriggerRequestPlayerStatePaused    VideoTriggerRequestPlayerState = "paused"
	VideoTriggerRequestPlayerStatePlaying   VideoTriggerRequestPlayerState = "playing"
)

// Defines values for VideoTriggerRequestPriority.
const (
	VideoTriggerRequestPriorityPersistent VideoTriggerRequestPriority = "persistent"
	VideoTriggerRequestPriorityTemporary  VideoTriggerRequestPriority = "temporary"
)

// Defines values for VideoTriggerRequestType.
const (
	VideoTriggerRequestTypeHls    VideoTriggerRequestType = "hls"
	VideoTriggerRequestTypeMjpeg  VideoTriggerRequestType = "mjpeg"
	VideoTriggerRequestTypeWebrtc VideoTriggerRequestType = "webrtc"
)

// Defines values for VoiceStateRequestState.
const (
	Error        VoiceStateRequestState = "error"
	Idle         VoiceStateRequestState = "idle"
	Listening    VoiceStateRequestState = "listening"
	Speaking     VoiceStateRequestState = "speaking"
	Synthesizing VoiceStateRequestState = "synthesizing"
	Thinking     VoiceStateRequestState = "thinking"
	Transcribing VoiceStateRequestState = "transcribing"
)

// ActionResponse defines model for ActionResponse.
type ActionResponse struct {
	Status string `json:"status"`
}

// AudioMuteRequest defines model for AudioMuteRequest.
type AudioMuteRequest struct {
	Muted *bool `json:"muted,omitempty"`
}

// AudioStateResponse defines model for AudioStateResponse.
type AudioStateResponse struct {
	Muted  bool   `json:"muted"`
	Status string `json:"status"`
	Volume int    `json:"volume"`
}

// AudioVolumeRequest defines model for AudioVolumeRequest.
type AudioVolumeRequest struct {
	Volume int `json:"volume"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error  string `json:"error"`
	Status string `json:"status"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// ListItem defines model for ListItem.
type ListItem struct {
	Assignee  *string   `json:"assignee"`
	CreatedAt time.Time `json:"created_at"`
	Done      bool      `json:"done"`
	DueDate   *string   `json:"due_date"`
	Id        string    `json:"id"`
	ListId    string    `json:"list_id"`
	Position  int       `json:"position"`
	Section   *string   `json:"section,omitempty"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ScreenAdvanceRequest defines model for ScreenAdvanceRequest.
type ScreenAdvanceRequest struct {
	// Direction Direction to advance screen (next or prev)
	Direction *ScreenAdvanceRequestDirection `json:"direction,omitempty"`
}

// ScreenAdvanceRequestDirection Direction to advance screen (next or prev)
type ScreenAdvanceRequestDirection string

// ScreenNavigationResponse defines model for ScreenNavigationResponse.
type ScreenNavigationResponse struct {
	CurrentScreen int    `json:"current_screen"`
	Status        string `json:"status"`
	TotalScreens  int    `json:"total_screens"`
}

// ScreenPauseRequest defines model for ScreenPauseRequest.
type ScreenPauseRequest struct {
	// DurationSeconds Seconds to suspend rotation before auto-resuming (0 = indefinitely)
	DurationSeconds *int `json:"duration_seconds,omitempty"`

	// Paused true to pause automatic rotation; false to resume
	Paused bool `json:"paused"`
}

// ScreenPauseResponse defines model for ScreenPauseResponse.
type ScreenPauseResponse struct {
	CurrentScreen int    `json:"current_screen"`
	Paused        bool   `json:"paused"`
	Status        string `json:"status"`
}

// ScreenSelectRequest defines model for ScreenSelectRequest.
type ScreenSelectRequest struct {
	// ScreenIndex 0-indexed screen number
	ScreenIndex int `json:"screen_index"`
}

// VideoActionRequest defines model for VideoActionRequest.
type VideoActionRequest struct {
	Action VideoActionRequestAction `json:"action"`
	Id     string                   `json:"id"`
	Value  *interface{}             `json:"value"`
}

// VideoActionRequestAction defines model for VideoActionRequest.Action.
type VideoActionRequestAction string

// VideoDismissRequest defines model for VideoDismissRequest.
type VideoDismissRequest struct {
	// Id Stream identifier to dismiss, or "all" / "*" to dismiss all active streams and return to widgets mode.
	Id string `json:"id"`
}

// VideoPlayerStateRequest defines model for VideoPlayerStateRequest.
type VideoPlayerStateRequest struct {
	Id          string                             `json:"id"`
	PlayerState VideoPlayerStateRequestPlayerState `json:"player_state"`
}

// VideoPlayerStateRequestPlayerState defines model for VideoPlayerStateRequest.PlayerState.
type VideoPlayerStateRequestPlayerState string

// VideoPlayerStateResponse defines model for VideoPlayerStateResponse.
type VideoPlayerStateResponse struct {
	Id          string                              `json:"id"`
	PlayerState VideoPlayerStateResponsePlayerState `json:"player_state"`
	Status      string                              `json:"status"`
}

// VideoPlayerStateResponsePlayerState defines model for VideoPlayerStateResponse.PlayerState.
type VideoPlayerStateResponsePlayerState string

// VideoStateResponse defines model for VideoStateResponse.
type VideoStateResponse struct {
	Mode    VideoStateResponseMode `json:"mode"`
	Pip     *VideoStream           `json:"pip,omitempty"`
	Primary *VideoStream           `json:"primary,omitempty"`
	Status  string                 `json:"status"`
}

// VideoStateResponseMode defines model for VideoStateResponse.Mode.
type VideoStateResponseMode string

// VideoStream defines model for VideoStream.
type VideoStream struct {
	ControlUrl     *string                 `json:"control_url,omitempty"`
	Controllable   *bool                   `json:"controllable,omitempty"`
	Id             string                  `json:"id"`
	Muted          *bool                   `json:"muted,omitempty"`
	PlayerState    *VideoStreamPlayerState `json:"player_state,omitempty"`
	Priority       *VideoStreamPriority    `json:"priority,omitempty"`
	StreamUrl      string                  `json:"stream_url"`
	TimeoutSeconds *int                    `json:"timeout_seconds,omitempty"`
	Type           VideoStreamType         `json:"type"`
}

// VideoStreamPlayerState defines model for VideoStream.PlayerState.
type VideoStreamPlayerState string

// VideoStreamPriority defines model for VideoStream.Priority.
type VideoStreamPriority string

// VideoStreamType defines model for VideoStream.Type.
type VideoStreamType string

// VideoTriggerRequest defines model for VideoTriggerRequest.
type VideoTriggerRequest struct {
	ControlUrl   *string `json:"control_url,omitempty"`
	Controllable *bool   `json:"controllable,omitempty"`

	// Id Unique stream identifier ("all" and "*" are reserved sentinels).
	Id             string                          `json:"id"`
	PlayerState    *VideoTriggerRequestPlayerState `json:"player_state,omitempty"`
	Priority       *VideoTriggerRequestPriority    `json:"priority,omitempty"`
	StreamUrl      string                          `json:"stream_url"`
	TimeoutSeconds *int                            `json:"timeout_seconds,omitempty"`
	Type           *VideoTriggerRequestType        `json:"type,omitempty"`
}

// VideoTriggerRequestPlayerState defines model for VideoTriggerRequest.PlayerState.
type VideoTriggerRequestPlayerState string

// VideoTriggerRequestPriority defines model for VideoTriggerRequest.Priority.
type VideoTriggerRequestPriority string

// VideoTriggerRequestType defines model for VideoTriggerRequest.Type.
type VideoTriggerRequestType string

// VoiceStateRequest defines model for VoiceStateRequest.
type VoiceStateRequest struct {
	Reply      *string                `json:"reply"`
	State      VoiceStateRequestState `json:"state"`
	Status     *string                `json:"status"`
	Transcript *string                `json:"transcript"`
	TtsEngine  *string                `json:"tts_engine"`
}

// VoiceStateRequestState defines model for VoiceStateRequest.State.
type VoiceStateRequestState string

// VoiceStateResponse defines model for VoiceStateResponse.
type VoiceStateResponse struct {
	Status string `json:"status"`
}

// WidgetPushResponse defines model for WidgetPushResponse.
type WidgetPushResponse struct {
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
	WidgetId  string    `json:"widget_id"`
}

// GetListItemsParams defines parameters for GetListItems.
type GetListItemsParams struct {
	// IncludeDone If false, filters out completed items (default true)
	IncludeDone *bool `form:"include_done,omitempty" json:"include_done,omitempty"`
}

// PostVoiceInteractMultipartBody defines parameters for PostVoiceInteract.
type PostVoiceInteractMultipartBody struct {
	// Audio Recorded 16 kHz mono PCM WAV audio file
	Audio openapi_types.File `json:"audio"`

	// NodeId Originating kiosk node identifier
	NodeId *string `json:"node_id,omitempty"`

	// SessionId Optional session or interaction correlation ID
	SessionId *string `json:"session_id,omitempty"`
}

// PostWidgetPushJSONBody defines parameters for PostWidgetPush.
type PostWidgetPushJSONBody map[string]interface{}

// PostAudioMuteJSONRequestBody defines body for PostAudioMute for application/json ContentType.
type PostAudioMuteJSONRequestBody = AudioMuteRequest

// PostAudioVolumeJSONRequestBody defines body for PostAudioVolume for application/json ContentType.
type PostAudioVolumeJSONRequestBody = AudioVolumeRequest

// PostScreenAdvanceJSONRequestBody defines body for PostScreenAdvance for application/json ContentType.
type PostScreenAdvanceJSONRequestBody = ScreenAdvanceRequest

// PostScreenPauseJSONRequestBody defines body for PostScreenPause for application/json ContentType.
type PostScreenPauseJSONRequestBody = ScreenPauseRequest

// PostScreenSelectJSONRequestBody defines body for PostScreenSelect for application/json ContentType.
type PostScreenSelectJSONRequestBody = ScreenSelectRequest

// PostVideoActionJSONRequestBody defines body for PostVideoAction for application/json ContentType.
type PostVideoActionJSONRequestBody = VideoActionRequest

// PostVideoDismissJSONRequestBody defines body for PostVideoDismiss for application/json ContentType.
type PostVideoDismissJSONRequestBody = VideoDismissRequest

// PostVideoStateJSONRequestBody defines body for PostVideoState for application/json ContentType.
type PostVideoStateJSONRequestBody = VideoPlayerStateRequest

// PostVideoTriggerJSONRequestBody defines body for PostVideoTrigger for application/json ContentType.
type PostVideoTriggerJSONRequestBody = VideoTriggerRequest

// PostVoiceInteractMultipartRequestBody defines body for PostVoiceInteract for multipart/form-data ContentType.
type PostVoiceInteractMultipartRequestBody PostVoiceInteractMultipartBody

// PostVoiceStateJSONRequestBody defines body for PostVoiceState for application/json ContentType.
type PostVoiceStateJSONRequestBody = VoiceStateRequest

// PostWidgetPushJSONRequestBody defines body for PostWidgetPush for application/json ContentType.
type PostWidgetPushJSONRequestBody PostWidgetPushJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get master audio state
	// (GET /api/audio)
	GetAudio(w http.ResponseWriter, r *http.Request)
	// Set or toggle master audio mute
	// (POST /api/audio/mute)
	PostAudioMute(w http.ResponseWriter, r *http.Request)
	// Set master audio volume
	// (POST /api/audio/volume)
	PostAudioVolume(w http.ResponseWriter, r *http.Request)
	// Get household list items
	// (GET /api/lists/{list_id}/items)
	GetListItems(w http.ResponseWriter, r *http.Request, listId string, params GetListItemsParams)
	// Advance screen sequentially
	// (POST /api/screen/advance)
	PostScreenAdvance(w http.ResponseWriter, r *http.Request)
	// Pause or resume automatic rotation
	// (POST /api/screen/pause)
	PostScreenPause(w http.ResponseWriter, r *http.Request)
	// Select screen by index
	// (POST /api/screen/select)
	PostScreenSelect(w http.ResponseWriter, r *http.Request)
	// Dispatch video transport action
	// (POST /api/video/action)
	PostVideoAction(w http.ResponseWriter, r *http.Request)
	// Dismiss video stream
	// (POST /api/video/dismiss)
	PostVideoDismiss(w http.ResponseWriter, r *http.Request)
	// Get video presentation state
	// (GET /api/video/state)
	GetVideoState(w http.ResponseWriter, r *http.Request)
	// Update video player transport state
	// (POST /api/video/state)
	PostVideoState(w http.ResponseWriter, r *http.Request)
	// Trigger video stream
	// (POST /api/video/trigger)
	PostVideoTrigger(w http.ResponseWriter, r *http.Request)
	// Coordinate voice interaction pipeline
	// (POST /api/voice/interact)
	PostVoiceInteract(w http.ResponseWriter, r *http.Request)
	// Update voice interaction lifecycle state
	// (POST /api/voice/state)
	PostVoiceState(w http.ResponseWriter, r *http.Request)
	// Push realtime widget payload
	// (POST /api/widgets/{widget_id}/push)
	PostWidgetPush(w http.ResponseWriter, r *http.Request, widgetId string)
	// Render widget HTML fragment
	// (GET /api/widgets/{widget_id}/render)
	GetWidgetRender(w http.ResponseWriter, r *http.Request, widgetId string)
	// Health check alias endpoint
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Health check endpoint
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Serve static widget package asset
	// (GET /widget-types/{type}/assets/{path})
	GetWidgetAsset(w http.ResponseWriter, r *http.Request, pType string, path string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAudio operation middleware
func (siw *ServerInterfaceWrapper) GetAudio(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAudio(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAudioMute operation middleware
func (siw *ServerInterfaceWrapper) PostAudioMute(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAudioMute(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAudioVolume operation middleware
func (siw *ServerInterfaceWrapper) PostAudioVolume(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAudioVolume(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetListItems operation middleware
func (siw *ServerInterfaceWrapper) GetListItems(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId string

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", r.PathValue("list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetListItemsParams

	// ------------- Optional query parameter "include_done" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_done", r.URL.Query(), &params.IncludeDone)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_done", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetListItems(w, r, listId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostScreenAdvance operation middleware
func (siw *ServerInterfaceWrapper) PostScreenAdvance(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostScreenAdvance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostScreenPause operation middleware
func (siw *ServerInterfaceWrapper) PostScreenPause(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostScreenPause(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostScreenSelect operation middleware
func (siw *ServerInterfaceWrapper) PostScreenSelect(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostScreenSelect(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostVideoAction operation middleware
func (siw *ServerInterfaceWrapper) PostVideoAction(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostVideoAction(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostVideoDismiss operation middleware
func (siw *ServerInterfaceWrapper) PostVideoDismiss(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostVideoDismiss(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVideoState operation middleware
func (siw *ServerInterfaceWrapper) GetVideoState(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVideoState(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostVideoState operation middleware
func (siw *ServerInterfaceWrapper) PostVideoState(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostVideoState(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostVideoTrigger operation middleware
func (siw *ServerInterfaceWrapper) PostVideoTrigger(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostVideoTrigger(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostVoiceInteract operation middleware
func (siw *ServerInterfaceWrapper) PostVoiceInteract(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostVoiceInteract(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostVoiceState operation middleware
func (siw *ServerInterfaceWrapper) PostVoiceState(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostVoiceState(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostWidgetPush operation middleware
func (siw *ServerInterfaceWrapper) PostWidgetPush(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "widget_id" -------------
	var widgetId string

	err = runtime.BindStyledParameterWithOptions("simple", "widget_id", r.PathValue("widget_id"), &widgetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "widget_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostWidgetPush(w, r, widgetId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWidgetRender operation middleware
func (siw *ServerInterfaceWrapper) GetWidgetRender(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "widget_id" -------------
	var widgetId string

	err = runtime.BindStyledParameterWithOptions("simple", "widget_id", r.PathValue("widget_id"), &widgetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "widget_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWidgetRender(w, r, widgetId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWidgetAsset operation middleware
func (siw *ServerInterfaceWrapper) GetWidgetAsset(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "type" -------------
	var pType string

	err = runtime.BindStyledParameterWithOptions("simple", "type", r.PathValue("type"), &pType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Path parameter "path" -------------
	var path string

	err = runtime.BindStyledParameterWithOptions("simple", "path", r.PathValue("path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWidgetAsset(w, r, pType, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/audio", wrapper.GetAudio)
	m.HandleFunc("POST "+options.BaseURL+"/api/audio/mute", wrapper.PostAudioMute)
	m.HandleFunc("POST "+options.BaseURL+"/api/audio/volume", wrapper.PostAudioVolume)
	m.HandleFunc("GET "+options.BaseURL+"/api/lists/{list_id}/items", wrapper.GetListItems)
	m.HandleFunc("POST "+options.BaseURL+"/api/screen/advance", wrapper.PostScreenAdvance)
	m.HandleFunc("POST "+options.BaseURL+"/api/screen/pause", wrapper.PostScreenPause)
	m.HandleFunc("POST "+options.BaseURL+"/api/screen/select", wrapper.PostScreenSelect)
	m.HandleFunc("POST "+options.BaseURL+"/api/video/action", wrapper.PostVideoAction)
	m.HandleFunc("POST "+options.BaseURL+"/api/video/dismiss", wrapper.PostVideoDismiss)
	m.HandleFunc("GET "+options.BaseURL+"/api/video/state", wrapper.GetVideoState)
	m.HandleFunc("POST "+options.BaseURL+"/api/video/state", wrapper.PostVideoState)
	m.HandleFunc("POST "+options.BaseURL+"/api/video/trigger", wrapper.PostVideoTrigger)
	m.HandleFunc("POST "+options.BaseURL+"/api/voice/interact", wrapper.PostVoiceInteract)
	m.HandleFunc("POST "+options.BaseURL+"/api/voice/state", wrapper.PostVoiceState)
	m.HandleFunc("POST "+options.BaseURL+"/api/widgets/{widget_id}/push", wrapper.PostWidgetPush)
	m.HandleFunc("GET "+options.BaseURL+"/api/widgets/{widget_id}/render", wrapper.GetWidgetRender)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc("GET "+options.BaseURL+"/widget-types/{type}/assets/{path}", wrapper.GetWidgetAsset)

	return m
}
